### ISSUE TITLE
FileNotFoundError on Webserver

### ISSUE THREAD

**Issue by elizabethmcd** [IBM/AutoPeptideML#29]
**Describe the bug**
When building a model with the downloaded sample dataset and selecting "blood-brain barrier crossing" for overlapping bioactivities, I get a FileNotFoundError: 

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/raulfd/peptide-webserver/projects/use_data/apml.txt'
File "/home/raulfd/miniconda3/envs/apml/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
File "/home/raulfd/peptide-webserver/projects/autopeptideml.py", line 871, in <module>
    home()
File "/home/raulfd/peptide-webserver/projects/autopeptideml.py", line 104, in home
    page_names_to_funcs[menu]()
File "/home/raulfd/peptide-webserver/projects/autopeptideml.py", line 543, in build_model
    run(df, search_negatives, bioactivities, alignment_algorithm, threshold)
File "/home/raulfd/peptide-webserver/projects/autopeptideml.py", line 175, in run
    with open(USE_DATA_PATH) as fi:
```

This also happens with files of my own, but is reproducible on my end with the downloaded sample dataset. 

**To Reproduce**
Used default options 

**Expected behavior**
I've been able to successfully run model building before and have never encountered this error.

**Screenshots**
<img width="1009" alt="Screenshot 2024-11-04 at 3 44 48 PM" src="https://github.com/user-attachments/assets/c3366e0b-a68d-4bcd-bc19-831144a6eaa5">

**Desktop (please complete the following information):**
- Browser: Chrome

**Comment by RaulFD-creator** [comment]
Hi @elizabethmcd, I introduced the bug when doing some maintenance in the webserver, I apologize for the inconvenience.

I fixed it and now it should run correctly, but please, try again and if the error persists or a new error appears, let me know. 

Thanks for bringing this issue to my attention!

**Comment by elizabethmcd** [comment]
It's working now as expected, thank you! And this is a fantastic tool, great work!!

**Comment by RaulFD-creator** [comment]
Thanks a lot for the kind words!  If there are any missing features that you'd like to see, please feel free to let us know
